name: Build and Release

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build application
        run: npm run build

      - name: Install electron-builder
        run: npm install electron-builder

      - name: Build Windows release
        run: npx electron-builder --win

      - name: Upload Windows artifacts
        uses: actions/upload-artifact@v3
        with:
          name: windows-release
          path: dist/

  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build application
        run: npm run build

      - name: Install electron-builder
        run: npm install electron-builder

      - name: Build macOS release
        run: npx electron-builder --mac

      - name: Upload macOS artifacts
        uses: actions/upload-artifact@v3
        with:
          name: macos-release
          path: dist/
